import { Inter } from "@next/font/google";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <button className="bg-primary font-bold text-white p-2 m-2 rounded-full hover:bg-primary-400 focus:bg-primary-600">
        Hello!World!
      </button>
    </>
  );
}
